### PR TITLE
Feature/save and gizmo macros

### PR DESCRIPTION
**Pull request by Dartemiss**
What's new?
- CTRL + S for saving the scene
- CTRL + Shift + S for saving scene as
- CTRL + O for opening/loading scene
- CTRL + N for new scene
- W/E/R for changing the current gizmo

### CODE REVIEW

**Review by marcorod94 — APPROVED** [review]
Good work but I have a question Is loading a scene while playing intended?

**Comment by Dartemiss** [comment]
> 
> 
> Good work but I have a question Is loading a scene while playing intended?

@marcorod94 Well I allowed it as when we are changing levels we are loading another scene so maybe for testing can be useful. But I don't know maybe we shouldn't allow it.

**Review by JorxSS — APPROVED** [review]

**Comment by JorxSS** [comment]
I'm agree with Marco, maybe could create some problems, Maybe we should not allow to load a scene while playing.

**Comment by Dartemiss** [comment]
I have changed now the code and loading scene is not allowed while game is running. @JorxSS @marcorod94

**Pull request merged**
