### PR TITLE
Feature/particle system improvements

### PR DESCRIPTION
**Pull request by JordiRomagosa**
Improvements in particle system and fixed some bugs:

- **Fixed** problem with **linear color blend**. Now can't surpass the maximum particle life and doesn't cause random colors to appear at the end.

- **Improved particle emission**. Now can spawn more than one particle per frame, allowing to implement effects that required lots of particles and were looking weird before due to frame-rate limited spawning.

- Changed Play, Pause and Stop, and fixed Emission. Now:
    - **Pause**: stops the particles in the place and doesn't spawn more.
    - **Stop**: stops particle emission but keeps particles moving. Ideal for particle effects that need to disappear over time (like attack particles). Before, after calling Stop, all the particles disappeared at the same time making it feel weird; and now they disappear as they reach their expected lifetime.
    - **Play**: resumes the particle movement after Pause, or restores the spawning after Stop.
    - **Emit**: doesn't interfere with normal particle behavior anymore, but restores particle movement if they were paused.
<br></br>
- Changed **Particle System Rendering** in editor. Now, **if the game isn't running**, only the currently selected particle system or billboard will be rendered. There's an option in Window>Config>Renderer to render all particle systems if needed. While not being rendered, particle systems are not being updated either.

- **Restored** old particle **orbit**. Like previously, it is **not finished** and doesn't allow for adjusting parameters, but it does apply an orbit into the particles. Needed for those particle systems that used orbit before, like the dust and leaf particles in scene 1.
- **Fixed** gravity and linear velocity over time.

### CODE REVIEW

**Review by yalania — CHANGES_REQUESTED** [review]
The billboard on level one don't work for me, maybe the way they change is affecting the code use to trigger them

**Comment by JordiRomagosa** [comment]
Yes, @yalania  thanks. It was a problem with the order of checking the conditions.

**Review by yalania — APPROVED** [review]
Gj, now is working correctly

**Review by Dartemiss — CHANGES_REQUESTED** [review]
With these changes the Emit of the particle system changes and on the boss avalanche this happens.
https://gyazo.com/350b7a7de08178fdeb4b65d890a0cae6

**Pull request merged**
